# Generated by Django 5.0.4 on 2024-04-18 21:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dotacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Escuadron',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombres', models.CharField(blank=True, max_length=100)),
                ('sigla', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='TipoDeDispositivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('value', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Funcionario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombres', models.CharField(blank=True, max_length=100)),
                ('apellidos', models.CharField(blank=True, max_length=100)),
                ('grado', models.CharField(blank=True, max_length=100)),
                ('codigo', models.CharField(blank=True, max_length=20)),
                ('cemep', models.CharField(blank=True, max_length=20)),
                ('extra', models.CharField(blank=True, max_length=20)),
                ('dotacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='servicios.dotacion')),
                ('escuadron', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='servicios.escuadron')),
            ],
        ),
        migrations.CreateModel(
            name='Servicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('funcionarios', models.ManyToManyField(to='servicios.funcionario')),
            ],
        ),
        migrations.AddField(
            model_name='dotacion',
            name='tipo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='servicios.tipodedispositivo'),
        ),
    ]
