# Generated by Django 5.0.4 on 2024-04-18 22:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0002_remove_escuadron_nombres_escuadron_nombre'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='funcionario',
            name='escuadron',
        ),
        migrations.CreateModel(
            name='Vehiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marca', models.CharField(max_length=100)),
                ('modelo', models.CharField(max_length=100)),
                ('placa', models.CharField(blank=True, max_length=20)),
                ('sigla', models.CharField(max_length=20)),
                ('dotacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='servicios.dotacion')),
            ],
        ),
    ]
